[package]
name = "omni_med_nexus_os"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
core_engine = { path = "../../core_engine" }
lazy_static = "1.5.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
