// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

BedStatus getRealtimeBedStatus() =>
    RustLib.instance.api.crateApiOperationalRedisGetRealtimeBedStatus();

class BedStatus {
  final int icuAvailable;
  final int generalAvailable;
  final int emergencyQueue;

  const BedStatus({
    required this.icuAvailable,
    required this.generalAvailable,
    required this.emergencyQueue,
  });

  @override
  int get hashCode =>
      icuAvailable.hashCode ^
      generalAvailable.hashCode ^
      emergencyQueue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BedStatus &&
          runtimeType == other.runtimeType &&
          icuAvailable == other.icuAvailable &&
          generalAvailable == other.generalAvailable &&
          emergencyQueue == other.emergencyQueue;
}
