// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

FinanceReport getFinancialSummary() =>
    RustLib.instance.api.crateApiStrategicFinanceGetFinancialSummary();

class FinanceReport {
  final double totalRevenue;
  final double pendingClaims;
  final double departmentExpenses;

  const FinanceReport({
    required this.totalRevenue,
    required this.pendingClaims,
    required this.departmentExpenses,
  });

  @override
  int get hashCode =>
      totalRevenue.hashCode ^
      pendingClaims.hashCode ^
      departmentExpenses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FinanceReport &&
          runtimeType == other.runtimeType &&
          totalRevenue == other.totalRevenue &&
          pendingClaims == other.pendingClaims &&
          departmentExpenses == other.departmentExpenses;
}
